services:
  ansible:
    build: .
    container_name: ansible
    image: ansible:latest
    volumes:
      - .:/ansible
     # - ~/.ssh:/root/.ssh:ro
    working_dir: /ansible
    environment:
      - ANSIBLE_HOST_KEY_CHECKING=false
    command: ansible-playbook -i inventories/production.yaml playbooks/master.yaml --ask-pass

