---
- name: Add entry to /etc/hosts
  hosts: masters, workers
  become: true  # To run tasks with elevated privileges
  tasks:
    - name: Add entry to /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ registry_domain }} docker-registry.mw.local"
        insertafter: EOF

